title: Adelle's Curated Space
description: portfolio space where summer projects cannot fit in the resume
theme: jekyll-theme-beautiful

url: "dellebew.github.io"

aux_links:
  Repository: github.com/dellebew/dellebew.github.io